blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name='blog'

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete")


    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name="home"),

    path('blog/',include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):

        return self.title

blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts=Post.objects.all()
        context={
            'posts':posts
        }
        return render(request, 'blog_list.html', context)


class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(request, 'blog_create.html', context)
    

    def post(self, request, *args, **kwargs):
        if request.method=="POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')

        context={
        }
        return render(request, 'blog_create.html', context)


class BlogDetailView(View):
    
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context={
            'post':post
        }
        return render(request, 'blog_detail.html', context)
    

class BlogUpdateView(UpdateView):
    model=Post
    fields=['title','content']
    template_name='blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})


class BlogDeleteView(DeleteView):
    model=Post
    template_name='blog_delete.html'
    success_url= reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render


class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={
            
        }
        return render(request, 'index.html',context)

templates/base.html
{% load static %}
{% load tailwind_tags %}
<head>
<html lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
    {% tailwind_css %}
                
    {% block extra_head %}{% endblock extra_head %}
        <title>{% block title %}{% endblock title %}</title>
</head>
<body class="bg-gray-100 dark:bg-dark-main  ">
    <div class="flex justify-center h-screen ">        
        <div class="w-full lg:w-2/3 xl:w-2/5 pt-32 lg:pt-16 px-2">
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}
{% block title %}CreateBlog{% endblock title %}


{% block content %}
<form class="form-horizontal dark:text-dark-txt" method="post"  enctype="multipart/form-data">
    <div class="mt-1 sm:mt-0 sm:col-span-2">
        {% csrf_token %}
        <div class="mt-4">
            <label for="first name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
            Title
            </label>
            {{form.title}}
            </div>
            <label for="last name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
            Content
            </label>
            <div>
                {{form.content}}
            </div> 
            
            <div class="control-group">
                <div class="controls">
                <a href="{% url "blog:home" %}" class="mt-4 inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-second bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
                Return</a>
                <button type="submit" class="mt-4 inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-third bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
                Save</button>
                </div>
            </div> 
           
    </div>    
</form>
{% endblock content %}

templates/blog_delete.html
{% extends 'base.html' %}
{% block title %}DeletePost{% endblock title %}

{% block content %}
    <div>
      <div class="bg-white dark:bg-dark-second shadow px-4 py-5 sm:rounded-lg sm:p-6">
        <div class="md:grid md:grid-cols-3 md:gap-6">
          <div class="md:col-span-1">
            <h3 class="text-lg font-medium leading-6 dark:text-dark-txt text-gray-900">Delete post</h3>
            <p class="mt-1 text-sm dark:text-dark-txt text-gray-500">
              Deleting this post means theres is no going back!
            </p>
          </div>
          <div class="mt-5 md:mt-0 md:col-span-2">
          
              <form  method="POST" class="space-y-8" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                  
                <div class="pt-5">
                        <div class="flex justify-end">
                        <a href="#" type="button" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            Cancel
                        </a>
                        <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white dark:bg-dark-third  bg-red-500 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                            Delete
                        </button>
                        </div>
                  </div>
              </form>
            
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

templates/blog_detail.html
{% extends 'base.html' %}
{% block title %}CreateBlog{% endblock title %}


{% block content %}
<div class="bg-white max-w-full dark:bg-dark-second shadow px-4 py-5 sm:rounded-lg sm:p-6">
    <div class="bg-white dark:bg-dark-third max-w-full px-4 py-5 border-b rounded-lg mb-2 dark:border-dark-second border-gray-200 sm:px-6">
        <h2 class="text-xl leading-6 cursor-default dark:text-dark-txt prose rounded font-bold text-gray-900">
        Detail Post
        </h2>
        <br>
        <label for="first name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
        Title
        </label>
        <p class="mt-1 text-sm cursor-default dark:text-dark-txt text-gray-500">{{post.title}}</p>
        <br>
        <label for="first name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
        Content
        </label>
        <p class="mt-1 text-sm cursor-default dark:text-dark-txt text-gray-500">{{post.content}}</p>
        <br>
        <a class="inline-flex items-center px-2.5 py-1.5 border bordindigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" href="{% url 'blog:home' %}">Return</a>
        
{% endblock content %}

templates/blog_list.html
{% extends 'base.html' %}
{% block title %}Blog{% endblock title %}

{% block content %}
<div class="bg-white max-w-full dark:bg-dark-second shadow px-4 py-5 sm:rounded-lg sm:p-6">
    <div class="bg-white dark:bg-dark-third max-w-full px-4 py-5 border-b rounded-lg mb-2 dark:border-dark-second border-gray-200 sm:px-6">
        <h2 class="text-xl leading-6 cursor-default dark:text-dark-txt prose rounded font-bold text-gray-900">
        Blog List
        </h2>
        <br>
        {%for post in posts%}
        <p class="mt-1 text-sm cursor-default dark:text-dark-txt text-gray-500">Blog:</p>
        <a class="items-center justify-center  rounded-full hover:bg-gray-200 dark:hover:bg-dark-third text-green-500 p1" href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
        <br>
        <a class="items-center justify-center  rounded-full hover:bg-gray-200 dark:hover:bg-dark-third text-blue-500 p1" href="{% url 'blog:update' post.id %}">Update</a>
        <br>
        <a class="items-center justify-center  rounded-full hover:bg-gray-200 dark:hover:bg-dark-third text-red-500 p1" href="{% url 'blog:delete' post.id %}">Delete</a>
        {%endfor%}
        <br>
        <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" href="{% url 'blog:create' %}">Create</a>
        
        <a href="{% url "home" %}" class="px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Cancel</a>
        

{% endblock content %}

templates/blog_update.html
{% extends 'base.html' %}
{% block title %}CreateBlog{% endblock title %}

{% block content %}
<form class="form-horizontal dark:text-dark-txt" method="post"  enctype="multipart/form-data">
    <div class="mt-1 sm:mt-0 sm:col-span-2">
        {% csrf_token %}
        <div class="mt-4">
            <label for="first name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
            Title
            </label>
            {{form.title}}
            </div>
            <label for="last name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
            Content
            </label>
            {{form.content}}

            
            <div class="control-group">
                <div class="controls">
                <a href="#" class="mt-4 inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-second bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
                Return to Profile </a>
                <button type="submit" class="mt-4 inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-third bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
                Update</button>
                </div>
            </div> 
        </div>    
    </div>    
</form>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Homepage{% endblock title %}

{% block content %}
<div class="bg-white max-w-full dark:bg-dark-second shadow px-4 py-5 sm:rounded-lg sm:p-6">
    <div class="bg-white dark:bg-dark-third max-w-full px-4 py-5 border-b rounded-lg mb-2 dark:border-dark-second border-gray-200 sm:px-6">
        <h1 class="text-xl leading-6 cursor-default dark:text-dark-txt prose rounded font-bold text-gray-900">
        Blog
        </h1>
            <p class="mt-1 text-sm cursor-default dark:text-dark-txt text-gray-500">hola, visita mi</p>
            <a class="items-center justify-center  rounded-full hover:bg-gray-200 dark:hover:bg-dark-third text-blue-500 p1" href="{% url 'blog:home' %}"> blog aqui.</a>
    </div>
</div>

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>